# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TableviewCellDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TableviewCellDemo

pod 'SDCycleScrollView', '~> 1.65'
pod 'Alamofire', '~> 4.1.0'
pod 'SwiftyJSON', '~> 3.1.3'
pod 'MJRefresh', '~> 3.1.12'
pod 'AFNetworking'
end